import { Opportunity, CountryDetail } from "../types";

export const MOCK_COUNTRIES: CountryDetail[] = [
  {
    id: "canada",
    name: "Canada",
    flagEmoji: "🇨🇦",
    immigrationPathways: "Express Entry (FSWP, FSTP, CEC), Provincial Nominee Programs (PNP), Atlantic Immigration Program, and Startup Visa.",
    averageSalary: "$65,000 - $95,000 CAD / year",
    costOfLiving: "Moderate to high (approx. $1,800 - $3,000 CAD/month excluding rent depending on the city).",
    popularIndustries: ["Software Engineering", "Healthcare & Nursing", "Civil & Mechanical Engineering", "Clean Energy", "Agriculture"],
    visaInformation: "Temporary Work Permits require an LMIA (Labour Market Impact Assessment). Post-Graduation Work Permits (PGWP) are available for international students.",
    educationOpportunities: "World-class universities (U of T, UBC, McGill) with strong research funds and pathways to permanent residency after graduation.",
    imageDescription: "Scenic view of Toronto skyline with CN Tower at sundown."
  },
  {
    id: "germany",
    name: "Germany",
    flagEmoji: "🇩🇪",
    immigrationPathways: "Opportunity Card (Chancenkarte) point system, Skilled Worker Visa, Blue Card EU, and Freelancer Visa.",
    averageSalary: "€48,000 - €75,000 / year",
    costOfLiving: "Moderate (approx. €1,100 - €1,800/month). Tuition at public universities is virtually free.",
    popularIndustries: ["Automotive Engineering", "IT & Cyber Security", "Renewable Energy", "Chemical & Pharmaceutical", "Advanced Manufacturing"],
    visaInformation: "Blue Card EU offers fast-track permanent residency (after 21-27 months) for high-salary specialists. German language proficiency boosts chances.",
    educationOpportunities: "Top technical colleges (TUM, KIT). English-taught Master's programs are abundant and highly respected globally.",
    imageDescription: "Classic Berlin Cathedral framed by clean modern streets."
  },
  {
    id: "uk",
    name: "United Kingdom",
    flagEmoji: "🇬🇧",
    immigrationPathways: "Skilled Worker Visa (Points-based system), Global Talent Visa, High Potential Individual (HPI) Visa, and Graduate Route.",
    averageSalary: "£40,000 - £70,000 / year",
    costOfLiving: "High (especially London, £1,500 - £2,800/month). Regionally moderate outside major cities.",
    popularIndustries: ["Finance & Fintech", "Data Science & AI", "Healthcare (NHS)", "Creative Arts & Media", "Biotechnology"],
    visaInformation: "Requires sponsorship from an approved UK employer. Global Talent Visa permits working without employer ties for exceptional achievements.",
    educationOpportunities: "Prestigious institutions (Oxford, Cambridge, Imperial). High quality of education and strong post-study global work pathways.",
    imageDescription: "Big Ben and Palace of Westminster reflecting on the Thames."
  },
  {
    id: "japan",
    name: "Japan",
    flagEmoji: "🇯🇵",
    immigrationPathways: "Specified Skilled Worker (SSW 1 & 2), Highly Skilled Professional (HSP) Visa, and General Work Visa.",
    averageSalary: "¥4,500,000 - ¥8,000,000 / year",
    costOfLiving: "Moderate in regional areas, high in Tokyo (approx. ¥150,000 - ¥280,000/month).",
    popularIndustries: ["Robotics & Automation", "Game Design & Animation", "Automotive", "Electronics", "Language Instruction"],
    visaInformation: "Requires a Certificate of Eligibility (COE) and corporate sponsorship. HSP Visa offers fast-track permanent residency in just 1 year.",
    educationOpportunities: "Universities like University of Tokyo and Kyoto University. Monbukagakusho (MEXT) scholarship is a fully-funded study pathway.",
    imageDescription: "Mount Fuji behind a beautiful pagoda in spring cherry blossoms."
  },
  {
    id: "australia",
    name: "Australia",
    flagEmoji: "🇦🇺",
    immigrationPathways: "General Skilled Migration (Subclass 189/190/491), Employer Nomination Scheme (Subclass 186/482), and Working Holiday Visa.",
    averageSalary: "$70,000 - $110,000 AUD / year",
    costOfLiving: "High (approx. $2,000 - $3,500 AUD/month). Excellent climate and outdoor lifestyle.",
    popularIndustries: ["Mining & Resource Extraction", "Construction Engineering", "Agricultural Tech", "Tourism & Hospitality", "Nursing & Aged Care"],
    visaInformation: "Expression of Interest (EOI) must be submitted through SkillSelect point-assessment. Age cap is generally under 45 for skilled programs.",
    educationOpportunities: "Group of Eight universities (ANU, Melbourne, Sydney) offer world-class environments, especially for Earth and Maritime Sciences.",
    imageDescription: "Sydney Opera House framed against blue skies and water."
  },
  {
    id: "usa",
    name: "United States",
    flagEmoji: "🇺🇸",
    immigrationPathways: "H-1B Specialty Occupation, L-1 Intra-company Transfer, EB-1/EB-2 NIW (National Interest Waiver) Green Cards, and O-1 Extraordinary Ability.",
    averageSalary: "$80,000 - $130,000 USD / year",
    costOfLiving: "Variable (very high in Silicon Valley / NYC, moderate in Midwest, $2,000 - $4,500 USD/month).",
    popularIndustries: ["Tech & Software", "Biomedical & Healthcare", "Aerospace Engineering", "Venture Capital & FinTech", "Entertainment"],
    visaInformation: "H-1B requires a lottery system. STEM OPT extension allows international science/math grads to work for up to 3 years without sponsorship.",
    educationOpportunities: "Ivy League and research powerhouses (MIT, Stanford). Immense venture capital and commercial startup validation ecosystems.",
    imageDescription: "The Golden Gate Bridge peeking through elegant morning fog."
  }
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 2,
    title: "Gates Cambridge Fully Funded Scholarship",
    organization: "Bill & Melinda Gates Foundation",
    country: "United Kingdom",
    category: "Scholarships",
    deadline: "2026-10-15",
    fundingAmount: "£18,000 stipend + full tuition covered",
    isFullyFunded: true,
    eligibility: "Citizens of any country outside the United Kingdom applying to pursue a full-time residential postgraduate degree or PhD at the University of Cambridge.",
    description: "Gates Cambridge Scholarships are highly prestigious awards for international postgraduate applicants. Outstanding academic record, strong leadership potential, and commitment to improving the lives of others are core criteria.",
    benefits: "Covers University Composition Fee, maintenance allowance (£18,000/year), inbound airfare at start/end of course, visa costs, alongside supplementary family or research allowances.",
    officialLink: "https://www.gatescambridge.org",
    datePosted: "2026-06-05",
    status: "APPROVED",
    isFeatured: true,
    visaSponsorship: true,
    remote: false,
    noIeltsRequired: false,
    govtSponsored: false,
    rating: 4.9
  },
  {
    id: 3,
    title: "CERN Openlab Summer Internship",
    organization: "CERN (European Organization for Nuclear Research)",
    country: "Switzerland",
    category: "Scholarships",
    deadline: "2026-12-15",
    fundingAmount: "3,200 CHF / Month allowance",
    isFullyFunded: true,
    eligibility: "Bachelor or Master students in Computer Science, Applied Mathematics, or Physics, who have completed at least 3 years of academic studies.",
    description: "Work on advanced computing projects in Geneva! Spend nine weeks during the summer working on a technical project and attending series of computing lectures specially prepared by IT experts at CERN.",
    benefits: "Monthly living allowance, round-trip travel allowance, health insurance coverage, organized social events, and hands-on guidance from leading scientists.",
    officialLink: "https://openlab.cern",
    datePosted: "2026-06-08",
    status: "APPROVED",
    isFeatured: false,
    visaSponsorship: true,
    remote: false,
    noIeltsRequired: true,
    govtSponsored: true,
    rating: 4.7
  },
  {
    id: 5,
    title: "German Chancenkarte Opportunity Card Program",
    organization: "German Federal Government",
    country: "Germany",
    category: "Immigration Programs",
    deadline: "2026-12-31",
    fundingAmount: "Job search visa (Self-funded)",
    isFullyFunded: false,
    eligibility: "Recognized university degree/vocational training, or score at least 6 points in the points system (based on German/English, age, professional experience, and links to Germany).",
    description: "The Chancenkarte (Opportunity Card) allows skilled workers from non-EU countries to enter Germany to seek professional employment without needing an active job contract first.",
    benefits: "Up to 12 months residency to seek qualified jobs, permission to work part-time up to 20 hours/week, and automatic transition to a permanent work visa upon securing employment.",
    officialLink: "https://www.make-it-in-germany.com",
    datePosted: "2026-05-15",
    status: "APPROVED",
    isFeatured: false,
    visaSponsorship: true,
    remote: false,
    noIeltsRequired: true,
    govtSponsored: true,
    rating: 4.3
  },
  {
    id: 6,
    title: "UN Youth Assembly Delegate Program",
    organization: "United Nations Association",
    country: "United States",
    category: "Conferences",
    deadline: "2026-08-15",
    fundingAmount: "Fully funded delegate positions available",
    isFullyFunded: true,
    eligibility: "Young leaders, social entrepreneurs, and youth advocates aged 18 to 32 who are actively working towards the UN Sustainable Development Goals.",
    description: "The UN Youth Assembly is parsed as the largest youth conference held in New York. Select delegates are granted full financial waivers to attend and present global impact initiatives.",
    benefits: "Round-trip airfare to New York City, hotel accommodation near UN Headquarters, delegate registration fees, meals, and participation in exclusive roundtables.",
    officialLink: "https://www.un.org/en/observances/youth-day",
    datePosted: "2026-06-07",
    status: "APPROVED",
    isFeatured: true,
    visaSponsorship: true,
    remote: false,
    noIeltsRequired: true,
    govtSponsored: true,
    rating: 4.8
  },
  {
    id: 7,
    title: "Y Combinator W27 Startup Funding",
    organization: "Y Combinator",
    country: "United States",
    category: "Startup Funding",
    deadline: "2026-09-10",
    fundingAmount: "$500,000 USD Seed Investment",
    isFullyFunded: false,
    eligibility: "Co-founders with high-potential tech prototypes, particularly in fields such as AI, biotechnology, SaaS, or decentralized developer frameworks.",
    description: "Y Combinator provides $500,000 USD seed funding, world-class mentorship, connections to top-tier international investors, and a lifelong global alumni community.",
    benefits: "$500,000 USD standard investment, intense 3-month acceleration program, presentation on Demo Day, and permanent access to Bookface community software tools.",
    officialLink: "https://www.ycombinator.com",
    datePosted: "2026-06-02",
    status: "APPROVED",
    isFeatured: true,
    visaSponsorship: true,
    remote: true,
    noIeltsRequired: true,
    govtSponsored: false,
    rating: 4.9
  },
  {
    id: 8,
    title: "Fulbright Foreign Student Program",
    organization: "US Department of State",
    country: "United States",
    category: "Scholarships",
    deadline: "2026-09-15",
    fundingAmount: "Fully Funded master's and PhD support",
    isFullyFunded: true,
    eligibility: "Foreign students from over 160 eligible developing/middle-income nations seeking postgraduate study in any subject inside the United States.",
    description: "Established in 1946, the flagship US international exchange program covers full master's/PhD programs. Promotes peaceful intercultural understanding through educational exchange.",
    benefits: "Full academic tuition, health and accident insurance (ASPE), J-1 visa assistance, return economy class flights, and a comprehensive monthly living math stipend.",
    officialLink: "https://foreign.fulbrightonline.org",
    datePosted: "2026-05-20",
    status: "APPROVED",
    isFeatured: false,
    visaSponsorship: true,
    remote: false,
    noIeltsRequired: false,
    govtSponsored: true,
    rating: 4.8
  }
];
